<a href="https://colab.research.google.com/github/KARTHIII023/SQL-CASESTUDY/blob/main/sql_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as ny
import pandas as pd
import requests

Task 1
Read the Population dataset from the CSV file.
Hint:
● Use the pandas library.
● Display the first five rows.
● Check the shape and data types.

In [ ]:

pop=pd.read_csv('/content/population.csv')
pop.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
pop.shape

(25, 2)

In [ ]:
pop.dtypes

country       object
population     int64
dtype: object

Task 2
Read the GDP dataset from the Excel file.
Hint:
● Use the appropriate pandas function.
● Display column names and data types.

In [ ]:

gdp=pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [ ]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

Task 3
Read the Internet Users dataset from the JSON file.
Hint:
● Use either the json module or pandas.
● Convert the data into a DataFrame

In [ ]:

intuser=pd.read_json("/content/internet_users.json")

In [ ]:
user=pd.DataFrame(intuser)
user

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Task 4
Read the Literacy Rate dataset from the XML file.
Hint:
● Use xml.etree.ElementTree or pandas.read_xml().
● Extract all required fields into a DataFrame.

In [ ]:
lits=pd.read_xml('/content/literacy_rate.xml')
lit=pd.DataFrame(lits)
lit

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Part B – Data Understanding
Task 5
Explore each dataset.
Find the following:
● Number of rows
● Number of columns
● Column names
● Data types
● Missing values
● Duplicate records

In [ ]:
pop.shape

(25, 2)

In [ ]:
gdp.shape

(25, 2)

In [ ]:
user.shape

(25, 2)

In [ ]:
lits.shape

(25, 2)

In [ ]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         25 non-null     object
 1   internet_users  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
lits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           25 non-null     object
 1   literacy_rate  25 non-null     float64
dtypes: float64(1), object(1)
memory usage: 532.0+ bytes

In [ ]:
pop.isnull().sum()

country       0
population    0
dtype: int64

In [ ]:
gdp.isnull().sum()

Country    0
GDP        0
dtype: int64

In [ ]:
lit.isnull().sum()

name             0
literacy_rate    0
dtype: int64

In [ ]:
user.isnull().sum()

country           0
internet_users    0
dtype: int64

In [ ]:
pop.duplicated().sum()

np.int64(0)

In [ ]:
gdp.duplicated().sum()

np.int64(0)

In [ ]:
lit.duplicated().sum()

np.int64(0)

In [ ]:
user.duplicated().sum()

np.int64(0)

Part C – Data Transformation
Task 6
Rename columns wherever necessary so that all datasets have a common column
name for merging.

In [ ]:
gdp.rename(columns={"Country":"country"}, inplace=True)
gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [ ]:
lit.rename(columns={"name":"country"}, inplace=True)
lit

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Task 7
Convert the required columns into appropriate numeric data types.
ALL IS IN INT

Task 8
Merge all four datasets into one DataFrame.

In [ ]:
merged = pd.merge(pop, gdp, on="country", how="inner")

In [ ]:
merged = pd.merge(merged, user, on="country", how="inner")

In [ ]:
merged = pd.merge(merged, lit, on="country", how="inner")

In [ ]:
merged

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

Task 9
Create the following calculated columns:
1. Internet Penetration (%)
2. GDP Per Capita

In [ ]:
merged["Internet_Penetration"] = (merged["internet_users"] / merged["population"]) * 100
merged["Internet_Penetration"]

0     94.259064
1     76.499240
2     61.594007
3     93.772832
4     94.905696
5     97.221797
6     94.984932
7     92.620425
8     94.723785
9     93.432326
10    85.152661
11    85.654888
12    96.561300
13    94.108029
14    79.111008
15    77.507019
16    97.662222
17    81.812620
18    72.502023
19    90.716446
20    97.470698
21    98.213417
22    97.552099
23    97.763593
24    95.720900
Name: Internet_Penetration, dtype: float64

In [ ]:
merged["gdp_per"] = merged["GDP"] / merged["population"]
merged["gdp_per"] = merged["gdp_per"].round(2)
merged

,country,population,GDP,internet_users,literacy_rate,Internet_Penetration,gdp_per
0,United States,331002651,30500000,312000000,99.0,94.259064,0.09
1,China,1411778724,19230000,1080000000,97.2,76.499240,0.01
2,India,1380004385,4187000,850000000,77.7,61.594007,0.00
3,Japan,125836021,4180000,118000000,99.0,93.772832,0.03
4,Germany,83240525,4744000,79000000,99.0,94.905696,0.06
5,United Kingdom,67886011,3839000,66000000,99.0,97.221797,0.06
6,France,65273511,3211000,62000000,99.0,94.984932,0.05
7,Italy,60461826,2420000,56000000,99.0,92.620425,0.04
8,Canada,38005238,2250000,36000000,99.0,94.723785,0.06
9,Australia,25687041,1880000,24000000,99.0,93.432326,0.07
10,Brazil,212559417,2330000,181000000,93.2,85.152661,0.01
11,Russia,145934462,2200000,125000000,99.7,85.654888,0.02
12,South Korea,51780579,1800000,50000000,98.8,96.561300,0.03
13,Spain,46754778,1710000,44000000,98.6,94.108029,0.04
14,Mexico,128932753,1810000,102000000,95.4,79.111008,0.01
15,Indonesia,273523615,1500000,212000000,96.0,77.507019,0.01
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.662222,0.03
17,Turkey,84339067,1350000,69000000,96.7,81.812620,0.02
18,South Africa,59308690,410000,43000000,95.0,72.502023,0.01
19,Argentina,45195774,640000,41000000,99.1,90.716446,0.01
20,Netherlands,17441139,1150000,17000000,99.0,97.470698,0.07
21,Switzerland,8654622,940000,8500000,99.0,98.213417,0.11
22,Sweden,10353442,650000,10100000,99.0,97.552099,0.06
23,Norway,5421241,580000,5300000,100.0,97.763593,0.11
24,Singapore,5850342,530000,5600000,97.5,95.720900,0.09

Part D – Load Data
Task 10
Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect("country_statistics.db")

In [ ]:
merged.to_sql(
    "country_statistics",
    conn,
    if_exists="replace",
    index=False
)

25

Task 11
Verify that the data has been loaded successfully.
Hint:
Retrieve the first five records from the SQLite table.

In [ ]:
query = "SELECT * FROM country_statistics LIMIT 5"
cursor = conn.cursor()
cursor.execute(query)
result = cursor.fetchall()
print(result)

[('United States', 331002651, 30500000, 312000000, 99.0, 94.25906380429564, 0.09), ('China', 1411778724, 19230000, 1080000000, 97.2, 76.49924040079244, 0.01), ('India', 1380004385, 4187000, 850000000, 77.7, 61.59400718136124, 0.0), ('Japan', 125836021, 4180000, 118000000, 99.0, 93.77283154876615, 0.03), ('Germany', 83240525, 4744000, 79000000, 99.0, 94.90569647416326, 0.06)]

1. List the Top 5 countries by GDP.

In [ ]:
merged.sort_values(by="GDP", ascending=False)[["country", "GDP"]].head(5)

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

2. List the Top 5 countries by population.

In [ ]:
merged.sort_values(by="population", ascending=False)[["country", "population"]].head(5)

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

3. Calculate the average literacy rate.

In [ ]:
merged["literacy_rate"].mean()

np.float64(97.248)

4. List all countries having a literacy rate greater than 90%.

In [ ]:
merged[merged["literacy_rate"] > 90][["country", "literacy_rate"]]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

5. List all countries having an internet penetration greater than 70%.

In [ ]:
merged[merged["Internet_Penetration"] > 70][["country", "Internet_Penetration"]]

           country  Internet_Penetration
0    United States             94.259064
1            China             76.499240
3            Japan             93.772832
4          Germany             94.905696
5   United Kingdom             97.221797
6           France             94.984932
7            Italy             92.620425
8           Canada             94.723785
9        Australia             93.432326
10          Brazil             85.152661
11          Russia             85.654888
12     South Korea             96.561300
13           Spain             94.108029
14          Mexico             79.111008
15       Indonesia             77.507019
16    Saudi Arabia             97.662222
17          Turkey             81.812620
18    South Africa             72.502023
19       Argentina             90.716446
20     Netherlands             97.470698
21     Switzerland             98.213417
22          Sweden             97.552099
23          Norway             97.763593
24       Singapore             95.720900

6. List the Top 5 countries by GDP per capita.

In [ ]:
merged.sort_values(by="gdp_per", ascending=False)[["country", "gdp_per"]].head(5)

          country  gdp_per
21    Switzerland     0.11
23         Norway     0.11
24      Singapore     0.09
0   United States     0.09
9       Australia     0.07

7. Calculate the total population represented in the dataset.

In [ ]:
merged["population"].sum()

np.int64(4720039725)

8. Calculate the average internet penetration across all countries.

In [ ]:
merged["Internet_Penetration"].mean()

np.float64(89.6609210897238)

9. Identify the country having the highest number of internet users.

In [ ]:
merged.sort_values(by="internet_users", ascending=False)[["country", "internet_users"]].head(1)

  country  internet_users
1   China      1080000000

10. Find the correlation between Literacy Rate and Internet Penetration.

In [ ]:
merged["literacy_rate"].corr(merged["Internet_Penetration"])

np.float64(0.7727536531179539)

11. Display the Top 5 countries by GDP.

In [ ]:
query1 = """
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
"""

cursor = conn.cursor()
cursor.execute(query1)
result = cursor.fetchall()
result

[('United States', 30500000),
 ('China', 19230000),
 ('Germany', 4744000),
 ('India', 4187000),
 ('Japan', 4180000)]

12. Find the average literacy rate.

In [ ]:
query2 = """
SELECT AVG(Literacy_Rate)
FROM country_statistics
"""

cursor = conn.cursor()
cursor.execute(query2)
result = cursor.fetchall()
result

[(97.24799999999999,)]

13. Display all countries having literacy rate above 90%.

In [ ]:
query3 = """
SELECT country, Literacy_Rate
FROM country_statistics
WHERE Literacy_Rate > 90
"""

cursor = conn.cursor()
cursor.execute(query3)
result = cursor.fetchall()
result

[('United States', 99.0),
 ('China', 97.2),
 ('Japan', 99.0),
 ('Germany', 99.0),
 ('United Kingdom', 99.0),
 ('France', 99.0),
 ('Italy', 99.0),
 ('Canada', 99.0),
 ('Australia', 99.0),
 ('Brazil', 93.2),
 ('Russia', 99.7),
 ('South Korea', 98.8),
 ('Spain', 98.6),
 ('Mexico', 95.4),
 ('Indonesia', 96.0),
 ('Saudi Arabia', 97.3),
 ('Turkey', 96.7),
 ('South Africa', 95.0),
 ('Argentina', 99.1),
 ('Netherlands', 99.0),
 ('Switzerland', 99.0),
 ('Sweden', 99.0),
 ('Norway', 100.0),
 ('Singapore', 97.5)]

14. Find the Top 5 countries with the highest internet penetration.

In [ ]:
query4 = """
SELECT country, Internet_Penetration
FROM country_statistics
ORDER BY Internet_Penetration DESC
LIMIT 5
"""

cursor = conn.cursor()
cursor.execute(query4)
result = cursor.fetchall()
result

[('Switzerland', 98.21341706200457),
 ('Norway', 97.7635932436872),
 ('Saudi Arabia', 97.66222204936648),
 ('Sweden', 97.55209909902428),
 ('Netherlands', 97.47069844463712)]

15. Calculate the total population.

In [ ]:
query5 = """
SELECT SUM(Population)
FROM country_statistics
"""

cursor = conn.cursor()
cursor.execute(query5)
result = cursor.fetchall()
result

[(4720039725,)]

16. Find the country with the highest GDP per capita.

In [ ]:
query6 = """
SELECT country, gdp_per
FROM country_statistics
ORDER BY gdp_per DESC
LIMIT 1
"""

cursor = conn.cursor()
cursor.execute(query6)
result = cursor.fetchall()
result

[('Switzerland', 0.11)]

17. Export the final merged dataset as a CSV file.

In [ ]:
merged.to_csv("country_statistics.csv", index=False)

In [ ]:
query = """
SELECT *
FROM country_statistics
ORDER BY gdp_per DESC
LIMIT 10
"""

cursor = conn.cursor()
cursor.execute(query)
result = cursor.fetchall()
result

[('Switzerland', 8654622, 940000, 8500000, 99.0, 98.21341706200457, 0.11),
 ('Norway', 5421241, 580000, 5300000, 100.0, 97.7635932436872, 0.11),
 ('United States',
  331002651,
  30500000,
  312000000,
  99.0,
  94.25906380429564,
  0.09),
 ('Singapore', 5850342, 530000, 5600000, 97.5, 95.72089973543427, 0.09),
 ('Australia', 25687041, 1880000, 24000000, 99.0, 93.43232644040238, 0.07),
 ('Netherlands', 17441139, 1150000, 17000000, 99.0, 97.47069844463712, 0.07),
 ('Germany', 83240525, 4744000, 79000000, 99.0, 94.90569647416326, 0.06),
 ('United Kingdom',
  67886011,
  3839000,
  66000000,
  99.0,
  97.22179728604175,
  0.06),
 ('Canada', 38005238, 2250000, 36000000, 99.0, 94.72378517929555, 0.06),
 ('Sweden', 10353442, 650000, 10100000, 99.0, 97.55209909902428, 0.06)]